// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Riglog.Api.Data.Sql;

namespace Riglog.Api.Data.Sql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210615190234_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.Computer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComputerTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("OsEditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OsTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OsVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComputerTypeId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OsEditionId");

                    b.HasIndex("OsTypeId");

                    b.HasIndex("OsVersionId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.ComputerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ComputerTypes");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.ComputerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("IsAdmin");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("ComputerUsers");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.OsEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OsVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OsVersionId");

                    b.ToTable("OsEditions");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.OsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("OsEditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OsEditionId");

                    b.ToTable("OsTypes");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.OsVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("OsVersions");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsSuperAdmin");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.Computer", b =>
                {
                    b.HasOne("Riglog.Api.Data.Sql.Entities.ComputerType", "ComputerType")
                        .WithMany("Computers")
                        .HasForeignKey("ComputerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riglog.Api.Data.Sql.Entities.OsEdition", "OsEdition")
                        .WithMany("Computers")
                        .HasForeignKey("OsEditionId");

                    b.HasOne("Riglog.Api.Data.Sql.Entities.OsType", "OsType")
                        .WithMany("Computers")
                        .HasForeignKey("OsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riglog.Api.Data.Sql.Entities.OsVersion", "OsVersion")
                        .WithMany("Computers")
                        .HasForeignKey("OsVersionId");

                    b.Navigation("ComputerType");

                    b.Navigation("OsEdition");

                    b.Navigation("OsType");

                    b.Navigation("OsVersion");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.ComputerUser", b =>
                {
                    b.HasOne("Riglog.Api.Data.Sql.Entities.Computer", "Computer")
                        .WithMany("ComputerUsers")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riglog.Api.Data.Sql.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Computer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.OsEdition", b =>
                {
                    b.HasOne("Riglog.Api.Data.Sql.Entities.OsVersion", "OsVersion")
                        .WithMany("OsEdition")
                        .HasForeignKey("OsVersionId");

                    b.Navigation("OsVersion");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.OsType", b =>
                {
                    b.HasOne("Riglog.Api.Data.Sql.Entities.OsEdition", "OsEdition")
                        .WithMany("OsTypes")
                        .HasForeignKey("OsEditionId");

                    b.Navigation("OsEdition");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.Computer", b =>
                {
                    b.Navigation("ComputerUsers");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.ComputerType", b =>
                {
                    b.Navigation("Computers");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.OsEdition", b =>
                {
                    b.Navigation("Computers");

                    b.Navigation("OsTypes");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.OsType", b =>
                {
                    b.Navigation("Computers");
                });

            modelBuilder.Entity("Riglog.Api.Data.Sql.Entities.OsVersion", b =>
                {
                    b.Navigation("Computers");

                    b.Navigation("OsEdition");
                });
#pragma warning restore 612, 618
        }
    }
}
